export interface Team {
    id: string;
    name: string;
    shortName: string;
    stadium: string;
    logoUrl: string;
  }
  
  export const EPL_TEAMS_DATA: Record<string, Team> = {
    ARS: { id: "ARS", name: "Arsenal", shortName: "ARS", stadium: "Emirates Stadium", logoUrl: "https://resources.premierleague.com/premierleague/badges/t3.png" },
    AVL: { id: "AVL", name: "Aston Villa", shortName: "AVL", stadium: "Villa Park", logoUrl: "https://resources.premierleague.com/premierleague/badges/t7.png" },
    BAR: { id: "BAR", name: "Barnsley", shortName: "BAR", stadium: "Oakwell", logoUrl: "https://www.footylogos.com/images/logos/Barnsley.png" },
    BIR: { id: "BIR", name: "Birmingham City", shortName: "BIR", stadium: "St Andrew's", logoUrl: "https://www.footylogos.com/images/logos/Birmingham_City.png" },
    BBR: { id: "BBR", name: "Blackburn Rovers", shortName: "BBR", stadium: "Ewood Park", logoUrl: "https://www.footylogos.com/images/logos/Blackburn_Rovers.png" },
    BLP: { id: "BLP", name: "Blackpool", shortName: "BLP", stadium: "Bloomfield Road", logoUrl: "https://www.footylogos.com/images/logos/Blackpool.png" },
    BOL: { id: "BOL", name: "Bolton Wanderers", shortName: "BOL", stadium: "Toughsheet Community Stadium", logoUrl: "https://www.footylogos.com/images/logos/Bolton_Wanderers.png" },
    BOU: { id: "BOU", name: "AFC Bournemouth", shortName: "BOU", stadium: "Vitality Stadium", logoUrl: "https://crests.football-data.org/bournemouth.png" },
    BRA: { id: "BRA", name: "Bradford City", shortName: "BRA", stadium: "Valley Parade", logoUrl: "https://www.footylogos.com/images/logos/Bradford_City.png" },
    BRE: { id: "BRE", name: "Brentford", shortName: "BRE", stadium: "Gtech Community Stadium", logoUrl: "https://resources.premierleague.com/premierleague/badges/t94.png" },
    BHA: { id: "BHA", name: "Brighton & Hove Albion", shortName: "BHA", stadium: "Amex Stadium", logoUrl: "https://resources.premierleague.com/premierleague/badges/t36.png" },
    BUR: { id: "BUR", name: "Burnley", shortName: "BUR", stadium: "Turf Moor", logoUrl: "https://resources.premierleague.com/premierleague/badges/t90.png" },
    CAR: { id: "CAR", name: "Cardiff City", shortName: "CAR", stadium: "Cardiff City Stadium", logoUrl: "https://www.footylogos.com/images/logos/Cardiff_City.png" },
    CHA: { id: "CHA", name: "Charlton Athletic", shortName: "CHA", stadium: "The Valley", logoUrl: "https://www.footylogos.com/images/logos/Charlton_Athletic.png" },
    CHE: { id: "CHE", name: "Chelsea", shortName: "CHE", stadium: "Stamford Bridge", logoUrl: "https://resources.premierleague.com/premierleague/badges/t8.png" },
    COV: { id: "COV", name: "Coventry City", shortName: "COV", stadium: "Coventry Building Society Arena", logoUrl: "https://crests.football-data.org/1076.png" },
    CRY: { id: "CRY", name: "Crystal Palace", shortName: "CRY", stadium: "Selhurst Park", logoUrl: "https://resources.premierleague.com/premierleague/badges/t31.png" },
    DER: { id: "DER", name: "Derby County", shortName: "DER", stadium: "Pride Park", logoUrl: "https://www.footylogos.com/images/logos/Derby_County.png" },
    EVE: { id: "EVE", name: "Everton", shortName: "EVE", stadium: "Hill Dickinson Stadium", logoUrl: "https://resources.premierleague.com/premierleague/badges/t11.png" },
    FUL: { id: "FUL", name: "Fulham", shortName: "FUL", stadium: "Craven Cottage", logoUrl: "https://resources.premierleague.com/premierleague/badges/t54.png" },
    HUD: { id: "HUD", name: "Huddersfield Town", shortName: "HUD", stadium: "John Smith's Stadium", logoUrl: "https://www.footylogos.com/images/logos/Huddersfield_Town.png" },
    HUL: { id: "HUL", name: "Hull City", shortName: "HUL", stadium: "MKM Stadium", logoUrl: "https://crests.football-data.org/322.png" },
    IPS: { id: "IPS", name: "Ipswich Town", shortName: "IPS", stadium: "Portman Road", logoUrl: "https://resources.premierleague.com/premierleague/badges/t40.png" },
    LEE: { id: "LEE", name: "Leeds United", shortName: "LEE", stadium: "Elland Road", logoUrl: "https://crests.football-data.org/341.png" },
    LEI: { id: "LEI", name: "Leicester City", shortName: "LEI", stadium: "King Power Stadium", logoUrl: "https://resources.premierleague.com/premierleague/badges/t13.png" },
    LIV: { id: "LIV", name: "Liverpool", shortName: "LIV", stadium: "Anfield", logoUrl: "https://resources.premierleague.com/premierleague/badges/t14.png" },
    LUT: { id: "LUT", name: "Luton Town", shortName: "LUT", stadium: "Kenilworth Road", logoUrl: "https://www.footylogos.com/images/logos/Luton_Town.png" },
    MCI: { id: "MCI", name: "Manchester City", shortName: "MCI", stadium: "Etihad Stadium", logoUrl: "https://resources.premierleague.com/premierleague/badges/t43.png" },
    MUN: { id: "MUN", name: "Manchester United", shortName: "MUN", stadium: "Old Trafford", logoUrl: "https://resources.premierleague.com/premierleague/badges/t1.png" },
    MID: { id: "MID", name: "Middlesbrough", shortName: "MID", stadium: "Riverside Stadium", logoUrl: "https://www.footylogos.com/images/logos/Middlesbrough.png" },
    NEW: { id: "NEW", name: "Newcastle United", shortName: "NEW", stadium: "St James' Park", logoUrl: "https://resources.premierleague.com/premierleague/badges/t4.png" },
    NOR: { id: "NOR", name: "Norwich City", shortName: "NOR", stadium: "Carrow Road", logoUrl: "https://www.footylogos.com/images/logos/Norwich_City.png" },
    NFO: { id: "NFO", name: "Nottingham Forest", shortName: "NFO", stadium: "City Ground", logoUrl: "https://crests.football-data.org/351.png" },
    OLD: { id: "OLD", name: "Oldham Athletic", shortName: "OLD", stadium: "Boundary Park", logoUrl: "https://www.footylogos.com/images/logos/Oldham_Athletic.png" },
    POR: { id: "POR", name: "Portsmouth", shortName: "POR", stadium: "Fratton Park", logoUrl: "https://www.footylogos.com/images/logos/Portsmouth.png" },
    QPR: { id: "QPR", name: "Queens Park Rangers", shortName: "QPR", stadium: "Loftus Road", logoUrl: "https://www.footylogos.com/images/logos/Queens_Park_Rangers.png" },
    REA: { id: "REA", name: "Reading", shortName: "REA", stadium: "Madejski Stadium", logoUrl: "https://www.footylogos.com/images/logos/Reading.png" },
    SHU: { id: "SHU", name: "Sheffield United", shortName: "SHU", stadium: "Bramall Lane", logoUrl: "https://www.footylogos.com/images/logos/Sheffield_United.png" },
    SHW: { id: "SHW", name: "Sheffield Wednesday", shortName: "SHW", stadium: "Hillsborough", logoUrl: "https://www.footylogos.com/images/logos/Sheffield_Wednesday.png" },
    SOU: { id: "SOU", name: "Southampton", shortName: "SOU", stadium: "St Mary's Stadium", logoUrl: "https://www.footylogos.com/images/logos/Southampton.png" },
    STK: { id: "STK", name: "Stoke City", shortName: "STK", stadium: "bet365 Stadium", logoUrl: "https://www.footylogos.com/images/logos/Stoke_City.png" },
    SUN: { id: "SUN", name: "Sunderland", shortName: "SUN", stadium: "Stadium of Light", logoUrl: "https://resources.premierleague.com/premierleague/badges/t56.png" },
    SWA: { id: "SWA", name: "Swansea City", shortName: "SWA", stadium: "Swansea.com Stadium", logoUrl: "https://www.footylogos.com/images/logos/Swansea_City.png" },
    SWI: { id: "SWI", name: "Swindon Town", shortName: "SWI", stadium: "County Ground", logoUrl: "https://www.footylogos.com/images/logos/Swindon_Town.png" },
    TOT: { id: "TOT", name: "Tottenham Hotspur", shortName: "TOT", stadium: "Tottenham Hotspur Stadium", logoUrl: "https://resources.premierleague.com/premierleague/badges/t6.png" },
    WAT: { id: "WAT", name: "Watford", shortName: "WAT", stadium: "Vicarage Road", logoUrl: "https://www.footylogos.com/images/logos/Watford.png" },
    WBA: { id: "WBA", name: "West Bromwich Albion", shortName: "WBA", stadium: "The Hawthorns", logoUrl: "https://www.footylogos.com/images/logos/West_Bromwich_Albion.png" },
    WHU: { id: "WHU", name: "West Ham United", shortName: "WHU", stadium: "London Stadium", logoUrl: "https://resources.premierleague.com/premierleague/badges/t21.png" },
    WIG: { id: "WIG", name: "Wigan Athletic", shortName: "WIG", stadium: "DW Stadium", logoUrl: "https://www.footylogos.com/images/logos/Wigan_Athletic.png" },
    WIM: { id: "WIM", name: "Wimbledon", shortName: "WIM", stadium: "Selhurst Park", logoUrl: "https://www.footylogos.com/images/logos/AFC_Wimbledon.png" },
    WOL: { id: "WOL", name: "Wolverhampton Wanderers", shortName: "WOL", stadium: "Molineux Stadium", logoUrl: "https://resources.premierleague.com/premierleague/badges/t39.png" },  
  };